projects:
  -
    name: 18app
    description: "18App e Carta Docente sono due programmi previsti dalla legge con i quali viene assegnato un bonus economico (€500) a determinate categorie di persone dette beneficiari (rispettivamente, tutti i 18enni e i docenti di ruolo) da spendere con specifici vincoli (in cultura e formazione) presso esercenti accreditati."
    website: https://www.18app.italia.it/
    documents:
      - 18app-esercenti-docs # la documentazione è dentro "/rst"
    logo: assets/images/logo-18app-512x512.png
  -
    name: Anagrafe Nazionale della Popolazione Residente
    short_name: ANPR
    description: "L’Anagrafe Nazionale della Popolazione Residente (ANPR) è la banca dati nazionale nella quale confluiranno progressivamente le anagrafi comunali."
    website: https://anpr.interno.it/
    documents:
      - anpr # la documentazione è dentro "/src"
    logo: assets/images/logo-anpr-256x256.png
    start_date:
    end_date:
    tags:
      - comuni
      - anagrafe
  -
    name: "Carta d'identità elettronica"
    short_name: CIE
    description: "La nuova Carta di identità elettronica è il documento personale che attesta l’identità del cittadino. È realizzata in materiale plastico, dalle dimensioni di una carta di credito e dotata di sofisticati elementi di sicurezza e di un microchip a radiofrequenza (RF) che memorizza i dati del titolare."
    website: https://www.cartaidentita.interno.gov.it/
    documents:
      - cie-middleware-windows-docs
  -
    name: "Data & Analytics Framework"
    short_name: DAF
    description: "Il Data & Analytics Framework è una delle attività atte a valorizzare il patrimonio informativo pubblico nazionale approvata dal Governo italiano nell’ambito del Piano Triennale per l’Informatica nella PA."
    website: https://github.com/italia/daf
    documents:
      - daf-piano-di-sviluppo # la documentazione è dentro "/rst"
      - daf-docs
      - lg-patrimonio-pubblico # la documentazione è dentro "/rst"
      - linee-guida-cataloghi-dati-dcat-ap-it
      - pianotri-schede-bdin
      - pianotri-elencobasidatichiave
      - daf-dataportal-it-docs
  -
    name: Designers Italia
    description: "Designers Italia è il punto di riferimento per il design della Pubblica Amministrazione: guide, strumenti e un forum per favorire la collaborazione e promuovere il ruolo dello human centered design nello sviluppo dei servizi pubblici."
    website: https://designers.italia.it/
    documents:
      - design-docs
      - writing-toolkit
      - design-scuole-docs
      - lg-competenzedigitali-docs
      - lg-comunicazione-docs
  -
    name: Developers Italia
    description: "La comunità degli sviluppatori che progettano e realizzano i servizi pubblici digitali in Italia"
    website: https://developers.italia.it/
    documents:
      - lg-acquisizione-e-riuso-software-per-pa-docs # il repo è sotto github.com/AGID
  -
    name: Dipartimento della Funzione Pubblica
    short_name: Funzione Pubblica
    description: "Il Dipartimento della funzione pubblica è una struttura della Presidenza del Consiglio dei ministri della Repubblica Italiana. Nell'ambito del Dipartimento opera l'Ispettorato per la funzione pubblica."
    website: http://www.funzionepubblica.gov.it/
    documents:
      - lg-misuraperformance-docs
      - foia-circolare2-docs
  -
    name: PagoPA
    short_name: PagoPA
    description: "PagoPA è il nodo di pagamenti della Pubblica Amministrazione. È una piattaforma che connette tra loro cittadini, Pubblica Amministrazione e i Prestatori di Servizi di Pagamento (PSP) per effettuare pagamenti verso la Pubblica Amministrazione in sicurezza e con semplicità."
    website: https://www.agid.gov.it/it/piattaforme/pagopa
    documents:
      - pagopa-specifichepagamenti-docs
      - pagopa-docs-faq
      - pagopa-codici-docs
      - lg-pagopa-docs
  -
    name: Piano Triennale per l'informatica nella Pubblica Amministrazione.
    short_name: Piano Triennale ICT
    description: "Il Piano Triennale è il documento di indirizzo strategico ed economico destinato a tutta la Pubblica Amministrazione che accompagna la trasformazione digitale del Paese."
    website: https://pianotriennale-ict.italia.it/
    documents:
      - pianotriennale-ict-doc
      - cad-docs
      - censimento-ict
      - cloud.italia.it
      - lg-modellointeroperabilita-docs
  -
    name: Relazioni commissioni parlamentari
    description: "Relazioni e documenti di commissioni parlamentari"
    documents:
      - relazionecommissionedigitale-docs
  -
    name: Sistema Pubblico di Identità Digitale
    short_name: SPID
    description: "SPID è una credenziale unica di accesso, con identità verificata, che può essere integrata secondo lo standard SAML su siti pubblici e privati."
    website: https://www.spid.gov.it/
    documents:
      - spid-regole-tecniche
  - 
    name: Docs Italia
    description: "Docs Italia è la piattaforma per i documenti tecnici e amministrativi della Pubblica Amministrazione"
    website: https://docs.italia.it
    documents:
      - docs-italia-guide
